Fixing parameter flag

diff --git a/.github/workflows/testing_docker.yaml b/.github/workflows/testing_docker.yaml
--- a/.github/workflows/testing_docker.yaml
+++ b/.github/workflows/testing_docker.yaml
@@ -59,9 +59,9 @@ jobs:
         run: |
               curl -sfL https://raw.githubusercontent.com/aswinkarthik/csvdiff/master/install.sh | sh -s -- -b ./csvdiff
               echo "Showing differences - if any"
-              ./csvdiff/csvdiff './test_data/canopycover.csv' './outputs/canopycover.csv' -columns 1 --primary-key 4 --format rowmark
+              ./csvdiff/csvdiff './test_data/canopycover.csv' './outputs/canopycover.csv' --columns 1 --primary-key 4 --format rowmark
               echo "Running check"
-              if [[ "$(./csvdiff/csvdiff './test_data/canopycover.csv' './outputs/canopycover.csv' -columns 1 --primary-key 4 --format rowmark 2>&1 | grep -A 5 'Rows:' | wc -l  | tr -d '[:space:]')" == "1" ]]; then echo "Test canopy cover content matches expected"; exit 0; else echo "Error - canopy cover contents mismatch from test_data/canopycover.csv"; exit 1; fi;
+              if [[ "$(./csvdiff/csvdiff './test_data/canopycover.csv' './outputs/canopycover.csv' --columns 1 --primary-key 4 --format rowmark 2>&1 | grep -A 5 'Rows:' | wc -l  | tr -d '[:space:]')" == "1" ]]; then echo "Test canopy cover content matches expected"; exit 0; else echo "Error - canopy cover contents mismatch from test_data/canopycover.csv"; exit 1; fi;
 
   artifact_cleanup:
     runs-on: ubuntu-latest
